# AgentGrapher

init_config:
  model_path: ".models/qwen2.5-coder-7b-instruct-q6_k.gguf"
  n_gpu_layers: -1
  n_ctx: 4096
  verbose: false

gen_config:
  max_tokens: 2048
  repeat_penalty: 1.05
  temperature: 0
  presence_penalty: 0.0
  min_p: 0.15

app_config:
  agent_name: "grapher"
  prompt_path: "src/configs/config-agents/grapher/prompt_grapher.yaml"
