# Local Clusterizer

init_config:
  model_name: "cointegrated/rubert-tiny2"
  device: "cpu"

gen_config:
  threshold: 0.5
  linkage: "complete"
  turn_on_connectivity: true
  metric: "cosine"
  n_clusters: null
