# AgentGlobalPlanner

init_config:
  model_path: ".models/T-lite-it-2.1-Q5_K_M.gguf"
  n_gpu_layers: -1
  n_ctx: 8192
  verbose: false

gen_config:
  max_tokens: 1024
  repeat_penalty: 1.05
  temperature: 0
  # top_p: 0.8
  # top_k: 20
  presence_penalty: 0.0
  min_p: 0.15

app_config:
  agent_name: "global_planner"
  prompt_path: "src/configs/config-agents/global_planner/prompt_global_planner.yaml"