# AgentSynthesizer

init_config:
  model_path: ".models/T-lite-it-2.1-Q5_K_M.gguf"
  n_gpu_layers: -1
  n_ctx: 16384
  verbose: false

gen_config:
  max_tokens: 2048
  repeat_penalty: 1.05
  temperature: 0
  presence_penalty: 0.0
  min_p: 0.15

app_config:
  agent_name: "synthesizer"
  prompt_path: "src/configs/config-agents/synthesizer/prompt_synthesizer.yaml"
  chunk_size_ratio: 0.7
  chunk_overlap_ratio: 0.25
  max_tokens_for_summary_ratio: 0.05
  max_history_tokens: 2.0
  max_tokens_for_compressed_summary_ratio: 0.15
